@host=localhost:8080
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbnRlclNob3c5MzcyIiwiZ2l2ZW5fbmFtZSI6IldpbGxpYW0iLCJmYW1pbHlfbmFtZSI6IldhdHNvbiIsImp0aSI6ImI2NDNjYTU4LThkMTEtNDQ2ZS04MjU3LTJhZTk1OTFjYWMzNCIsImV4cCI6MTcyNjYyNDg0OSwiaXNzIjoiSGlnaGxvYWRTb2NpYWwiLCJhdWQiOiJIaWdobG9hZFNvY2lhbCJ9.nw-Y4ZhFXhIzNtIPgKfNZx0L5zBd4j1M4-VAPSU69wY

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "EnterShow9372",
  "password": "password"
}

### List
GET http://{{host}}/post/list
Content-Type: application/json
Authorization: Bearer {{token}}

### Feed
GET http://{{host}}/post/feed?offset=0&limit=999
Content-Type: application/json
Authorization: Bearer {{token}}